version: "3"

services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - simple-network

  barbly_api:
    container_name: barbly_api
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/app/node_modules
    networks:
      - simple-network

networks:
  simple-network:
    driver: bridge

volumes:
  postgres:
